HF_MODEL_DIR=...
CHECKPOINT_DIR=...
STEP=...
TARGET_DIR=...

python scripts/model_merger.py \
    --backend fsdp \
    --hf_model_path $HF_MODEL_DIR \
    --local_dir $CHECKPOINT_DIR/global_step_$STEP/actor \
    --target_dir $TARGET_DIR \

cp $HF_MODEL_DIR/tokenizer* $TARGET_DIR
